apiVersion: v1
kind: Service
metadata:
  name: journal-preview
  labels:
    app: journal
spec:
  type: ClusterIP
  selector:
    app: journal
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
