apiVersion: v1
kind: Secret
metadata:
  name: journal
  labels:
    app: journal
type: Opaque
data:
  API_KEY: {{ .Values.secrets.API_KEY | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.DB_PASSWORD | b64enc | quote }}
