apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: journal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kalebcastillo/aks-delivery-platform
    targetRevision: HEAD
    path: k8s/journal
    helm:
      releaseName: journal
      valueFiles:
      - "prod-secrets.yaml"
      values: |
        replicaCount: 1
        
        configMap:
          LOG_LEVEL: "info"
          APP_ENV: "production"
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
