apiVersion: v2
name: journal
description: Helm chart for Journal application with API and database

type: application

# This is the chart version. This version number should be incremented each time you make changes
version: 0.1.0

# This is the version number of the application being deployed.
appVersion: "2.0"
